language: R
R:
  - 3.6
  - release

os:
  - linux
arch:
  - x64
dist:
  - bionic

r_packages:
  - reticulate
  - testthat
cache:
  packages: true
  directories:
    - "$HOME/.cache/pip"
addons:
  apt:
    sources: ubuntu-toolchain-r-test

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - which pip
  - Rscript -e "reticulate::py_config()"
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user --upgrade jax jaxlib

pandoc: true
latex: false

warnings_are_errors: false

notifications:
  email: false
