language: R
R:
  - 3.6

os:
  - linux
arch:
  - x64
dist:
  - bionic

r_packages:
  - reticulate
  - testthat

cache:
  packages: true
  directories:
    - "$HOME/.cache/pip"

addons:
  apt:
    packages:
      - python3-dev
      - python3-pip

before_install:
  - pip3 install --user numpy
  - pip3 install --user scipy
  - pip3 install --user --upgrade jax jaxlib

pandoc: true
latex: false

warnings_are_errors: false

notifications:
  email: false
