language: R
R:
  - 3.5
  - 3.6
  - release

os:
  - linux
arch:
  - x64
dist:
  - bionic
env:
  global:
    - PATH=/opt/python/3.8.1/bin:$PATH

r_packages:
  - reticulate
  - testthat

cache:
  packages: true
  directories:
    - "$HOME/.cache/pip"

before_install:
  - pip3 install --user numpy
  - pip3 install --user scipy
  - pip3 install --user --upgrade jax jaxlib

pandoc: true
latex: false

warnings_are_errors: false

notifications:
  email: false
